apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seedbox
resources:
  - ../common
  - service.yaml
  - sts.yaml
  - ingress.yaml
commonLabels:
  app: plex
configMapGenerator:
  - name: common-env
    behavior: merge
    envs:
      - .env