apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seedbox
resources:
  - ../common
  - airsonic-secrets.yaml
  - service.yaml
  - sts.yaml
  - ingress.yaml
commonLabels:
  app: airsonic
components:
  - ../components/authelia-middleware