kind: PersistentVolume
apiVersion: v1
metadata:
  name: localtime
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/localtime"