apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seedbox
resources:
  - ../common
  - secrets.yaml
  - service.yaml
  - ingress.yaml
  - sts.yaml
configMapGenerator:
  - name: common-env
    behavior: merge
    envs:
      - .env
commonLabels:
  app: transmission
components:
  - ../components/authelia-middleware